use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // 生成 C 头文件
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let mut config = cbindgen::Config::default();
    
    config.language = cbindgen::Language::C;
    config.header = Some("/* Auto-generated by cbindgen. Do not modify. */\n".to_string());
    config.include_guard = Some("CRYPTO_H".to_string());
    config.cpp_compat = true;
    config.enumeration = cbindgen::EnumConfig {
        enum_class: false,
        ..Default::default()
    };
    
    let out_path = PathBuf::from(&crate_dir).join("include");
    fs::create_dir_all(&out_path).expect("Failed to create include directory");
    
    let header_path = out_path.join("crypto.h");
    
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&header_path);
    
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=src/crypto.rs");
}