/* Auto-generated by cbindgen. Do not modify. */


#ifndef CRYPTO_H
#define CRYPTO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CKeyPair {
  char *public_key;
  char *private_key;
} CKeyPair;

typedef struct CByteArray {
  uint8_t *data;
  size_t len;
} CByteArray;

typedef struct CEncryptedData {
  char *ciphertext;
  char *nonce;
  char *tag;
} CEncryptedData;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct CKeyPair *crypto_generate_rsa_keypair(int bits);

struct CByteArray *crypto_rsa_encrypt(const char *public_key,
                                      const uint8_t *plaintext,
                                      size_t plaintext_len,
                                      size_t *out_len);

struct CByteArray *crypto_rsa_decrypt(const char *private_key,
                                      const uint8_t *ciphertext,
                                      size_t ciphertext_len,
                                      size_t *out_len);

struct CEncryptedData *crypto_aes_gcm_encrypt(const uint8_t *key,
                                              size_t key_len,
                                              const uint8_t *plaintext,
                                              size_t plaintext_len);

struct CByteArray *crypto_aes_gcm_decrypt(const uint8_t *key,
                                          size_t key_len,
                                          const struct CEncryptedData *encrypted_data,
                                          size_t *out_len);

struct CByteArray *crypto_generate_aes_key(size_t *out_len);

void crypto_free_keypair(struct CKeyPair *keypair);

void crypto_free_encrypted_data(struct CEncryptedData *data);

void crypto_free_byte_array(struct CByteArray *array);

const char *crypto_get_version(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* CRYPTO_H */
